backend:
  name: github
  repo: eternasuno/blog
  branch: main
  base_url: https://eterna-suno.vercel.app
  squash_merges: true
  commit_messages:
    create: "[Decap] Create {{collection}} {{slug}}"
    update: "[Decap] Update {{collection}} {{slug}}"
    delete: "[Decap] Delete {{collection}} {{slug}}"
    uploadMedia: "[Decap] Upload {{path}}"
    deleteMedia: "[Decap] Delete {{path}}"
    openAuthoring: "[Decap] {{message}}"
publish_mode: editorial_workflow
media_folder: public/media
public_folder: /media
site_url: https://eterna-suno.vercel.app
slug:
  encoding: ascii
  clean_accents: true
editor:
  preview: false
collections:
  - name: metadata
    label: Metadata
    delete: false
    format: json
    files:
    - label: Metadata
      name: metadata
      file: contents/metadata.json
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Creator, name: creator, widget: string }
        - { label: Description, name: description, widget: string }
        - { label: Host, name: host, widget: string }
        - { label: Tags, name: tags, widget: list, min: 1 }
  - name: posts
    label: Posts
    folder: contents/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}"
    preview_path: "{{dirname}}/{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - label: Tags
        name: tags
        widget: relation
        collection: metadata
        value_field: tags
        search_fields: [tags]
        multiple: true
        min: 1
      - { label: Content, name: body, widget: markdown }